### ISSUE TITLE
Caractères "illégaux" dans les noms de dossiers sont omis

### ISSUE THREAD

**Issue by rakruk** [sebastienlabine/clone-moodle#10]
L'implémentation de la restriction des caractères est incomplète, le programme essaie d’accéder à un dossier qui contient un caractère illégal (et est donc impossible), alors qu'il a crée un dossier qui ne contient pas ce caractère.

Un exemple pour montrer de quoi je parle:
![conemu64_2019-02-07_11-31-31](https://user-images.githubusercontent.com/43119833/52426422-f2199000-2acb-11e9-8a1a-be39ba32f6cd.png)

**Comment by sebastienlabine** [comment]
Le problème est en fait que le dossier est créer avec un nom "cleaned", mais lorsque j'essaye d'y accéder, j'utilise le nom de dossier pas cleaned. Should be fixed.

Laisse moi savoir si ça fonctionne!

**Comment by rakruk** [comment]
Ca semble fonctionner je n'ai plus d'erreurs comme celle-ci 👍
